version: "3"
services:
  h0:
    build: .
    command: "bin/main -i 0 -p 3000 -c 1:10.5.0.101:3000 -c 2:10.5.0.102:3000"
    networks:
      handoff:
        ipv4_address: 10.5.0.100
  h1:
    build: .
    command: "bin/main -i 1 -p 3000 -c 0:10.5.0.100:3000 -c 2:10.5.0.102:3000"
    networks:
      handoff:
        ipv4_address: 10.5.0.101
  h2:
    build: .
    command: "bin/main -i 2 -p 3000 -c 0:10.5.0.100:3000 -c 1:10.5.0.101:3000"
    networks:
      handoff:
        ipv4_address: 10.5.0.102

networks:
  handoff:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
