version: "3"
services:
  handoff0:
    image: vitorenesduarte/exactly-once
    command: "bin/main -i 0 -p 3000 -c 1:10.5.0.101:3000 -c 2:10.5.0.102:3000"
    networks:
      handoff:
        ipv4_address: 10.5.0.100
  handoff1:
    image: vitorenesduarte/exactly-once
    command: "bin/main -i 1 -p 3000 -c 0:10.5.0.100:3000 -c 2:10.5.0.102:3000"
    networks:
      handoff:
        ipv4_address: 10.5.0.101
  handoff2:
    image: vitorenesduarte/exactly-once
    command: "bin/main -i 2 -p 3000 -c 0:10.5.0.100:3000 -c 1:10.5.0.101:3000"
    networks:
      handoff:
        ipv4_address: 10.5.0.102
  pumba0:
    image: vitorenesduarte/exactly-once
    command: "bin/pumba_test -i 0 -p 3000 -c 1:10.5.0.101:3000"
    networks:
      handoff:
        ipv4_address: 10.5.0.100
  pumba1:
    image: vitorenesduarte/exactly-once
    command: "bin/pumba_test -i 1 -p 3000 -c 0:10.5.0.100:3000"
    networks:
      handoff:
        ipv4_address: 10.5.0.101

networks:
  handoff:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
